# Generated by Django 3.0.4 on 2020-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200811_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
